"""design profiler engine tables

Revision ID: 107430e27c2c
Revises: c9e4f1a82b6d
Create Date: 2026-06-12 14:20:57.685932

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '107430e27c2c'
down_revision: str | None = 'c9e4f1a82b6d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiler_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.Enum('whole_house', 'rooms', 'elements', name='profiler_scope'), server_default='whole_house', nullable=False),
    sa.Column('status', sa.Enum('not_started', 'intake_started', 'collecting_inputs', 'ranking', 'ai_interpreting', 'needs_clarification', 'theme_suggested', 'homeowner_review', 'revision_requested', 'architect_review', 'contractor_brief_ready', 'approved', 'locked', name='profiler_status'), server_default='not_started', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiler_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('area_kind', sa.Enum('house_build', 'interior', 'element', name='profiler_area_kind'), nullable=False),
    sa.Column('area_key', sa.String(length=64), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=True),
    sa.Column('component_id', sa.UUID(), nullable=True),
    sa.Column('recommended_count', sa.Integer(), server_default='6', nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'ready', name='profiler_area_status'), server_default='not_started', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), server_default='0', nullable=False),
    sa.Column('has_conflict', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('taste_model', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiler_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiler_contributors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'co_owner', 'family', 'advisor', 'architect', name='profiler_contributor_role'), nullable=False),
    sa.Column('is_decision_owner', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['homeowner_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiler_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiler_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('upload', 'camera', 'pinterest_link', 'pinterest_oauth', 'preset', name='profiler_reference_source'), nullable=False),
    sa.Column('image_r2_key', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('preset_id', sa.String(length=64), nullable=True),
    sa.Column('consistency_status', sa.Enum('consistent', 'tension', 'conflict', name='profiler_consistency_status'), nullable=True),
    sa.Column('consistency_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['profiler_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['profiler_contributors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiler_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiler_rankings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='{"positive": [], "negative": []}', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['profiler_contributors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_id'], ['profiler_references.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id', 'contributor_id', name='uq_profiler_ranking_ref_contributor')
    )
    op.create_table('profiler_reference_attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), server_default='0', nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['profiler_references.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiler_reference_attributes')
    op.drop_table('profiler_rankings')
    op.drop_table('profiler_references')
    op.drop_table('profiler_contributors')
    op.drop_table('profiler_areas')
    op.drop_table('profiler_profiles')

    # Autogenerate does not drop named enums — drop them explicitly.
    from sqlalchemy.dialects import postgresql

    for enum_name in (
        "profiler_scope",
        "profiler_status",
        "profiler_area_kind",
        "profiler_area_status",
        "profiler_contributor_role",
        "profiler_reference_source",
        "profiler_consistency_status",
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
