"""profiler brief + clarifications + membrane

Revision ID: 482859acb013
Revises: 7c55e0bf1599
Create Date: 2026-06-12 19:39:13.161062

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '482859acb013'
down_revision: str | None = '7c55e0bf1599'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'profiler_briefs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('profile_id', sa.UUID(), nullable=False),
        sa.Column('version', sa.Integer(), server_default='1', nullable=False),
        sa.Column(
            'state',
            sa.Enum(
                'homeowner_review',
                'revision_requested',
                'architect_review',
                'contractor_brief_ready',
                'approved',
                'locked',
                name='profiler_brief_state',
            ),
            server_default='homeowner_review',
            nullable=False,
        ),
        sa.Column(
            'summary_json',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{}',
            nullable=False,
        ),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['profile_id'], ['profiler_profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'profiler_brief_approvals',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('brief_id', sa.UUID(), nullable=False),
        sa.Column('actor_member_id', sa.UUID(), nullable=True),
        sa.Column('actor_user_id', sa.UUID(), nullable=True),
        sa.Column('actor_role', sa.String(length=32), nullable=False),
        sa.Column(
            'action',
            sa.Enum(
                'approve',
                'request_changes',
                'send_to_architect',
                'architect_sign_off',
                'contractor_received',
                name='profiler_brief_action',
            ),
            nullable=False,
        ),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['actor_member_id'], ['homeowner_members.id'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['brief_id'], ['profiler_briefs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'profiler_brief_renderings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('brief_id', sa.UUID(), nullable=False),
        sa.Column(
            'audience',
            sa.Enum(
                'homeowner',
                'architect',
                'contractor',
                name='profiler_brief_audience',
            ),
            nullable=False,
        ),
        sa.Column('scope', sa.String(length=16), server_default='whole_house', nullable=False),
        sa.Column('area_id', sa.UUID(), nullable=True),
        sa.Column(
            'content_json',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{}',
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['area_id'], ['profiler_areas.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['brief_id'], ['profiler_briefs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'profiler_clarifications',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('profile_id', sa.UUID(), nullable=False),
        sa.Column('area_id', sa.UUID(), nullable=True),
        sa.Column('contributor_id', sa.UUID(), nullable=True),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('answer', sa.Text(), nullable=True),
        sa.Column(
            'source_attribution',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{}',
            nullable=False,
        ),
        sa.Column(
            'asked_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['area_id'], ['profiler_areas.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['contributor_id'], ['profiler_contributors.id'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(['profile_id'], ['profiler_profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiler_clarifications')
    op.drop_table('profiler_brief_renderings')
    op.drop_table('profiler_brief_approvals')
    op.drop_table('profiler_briefs')
    for enum_name in (
        'profiler_brief_action',
        'profiler_brief_audience',
        'profiler_brief_state',
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
