"""profiler themes + conflicts

Revision ID: 7c55e0bf1599
Revises: 107430e27c2c
Create Date: 2026-06-12 18:17:40.987239

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c55e0bf1599'
down_revision: str | None = '107430e27c2c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiler_conflicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('contributor_a_id', sa.UUID(), nullable=True),
    sa.Column('contributor_b_id', sa.UUID(), nullable=True),
    sa.Column(
        'resolution_status',
        sa.Enum('open', 'resolved', 'deferred_to_architect', name='profiler_conflict_status'),
        server_default='open',
        nullable=False,
    ),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['profiler_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(
        ['contributor_a_id'], ['profiler_contributors.id'], ondelete='SET NULL'
    ),
    sa.ForeignKeyConstraint(
        ['contributor_b_id'], ['profiler_contributors.id'], ondelete='SET NULL'
    ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiler_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiler_themes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), server_default='0', nullable=False),
    sa.Column(
        'palette', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False
    ),
    sa.Column(
        'materials', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False
    ),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column(
        'evidence_reference_ids',
        postgresql.JSONB(astext_type=sa.Text()),
        server_default='[]',
        nullable=False,
    ),
    sa.Column(
        'status',
        sa.Enum('suggested', 'approved', 'adjusted', 'rejected', name='profiler_theme_status'),
        server_default='suggested',
        nullable=False,
    ),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['area_id'], ['profiler_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiler_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiler_themes')
    op.drop_table('profiler_conflicts')
    for enum_name in ('profiler_theme_status', 'profiler_conflict_status'):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
