"""phase B0 foundation: payments permits decisions baselines embeddings + user.language

Revision ID: b9b464b07c0b
Revises: 5e049b843974
Create Date: 2026-05-29 16:50:44.615690

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9b464b07c0b"
down_revision: str | None = "5e049b843974"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # event_embeddings needs pgvector. 0001 already enables it; keep this
    # defensive so the migration is safe even if run against a DB without it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "approval", "homeowner_question", "hold_payment", "generic", name="decision_kind"
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("raised_by", sa.UUID(), nullable=True),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "acknowledged",
                "resolved",
                "rejected",
                "escalated",
                name="decision_state",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column(
            "evidence_event_ids", postgresql.ARRAY(sa.UUID()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "permits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("permit_type", sa.Text(), nullable=False),
        sa.Column("authority", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "not_started",
                "applied",
                "under_review",
                "approved",
                "rejected",
                "expired",
                name="permit_status",
            ),
            server_default="not_started",
            nullable=False,
        ),
        sa.Column("applied_on", sa.Date(), nullable=True),
        sa.Column("expected_on", sa.Date(), nullable=True),
        sa.Column("decided_on", sa.Date(), nullable=True),
        sa.Column("expiry_on", sa.Date(), nullable=True),
        sa.Column("reference_no", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "site_baselines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("expected_daily_headcount", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id"),
    )
    op.create_table(
        "event_embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_event_id", sa.UUID(), nullable=False),
        sa.Column("embedding", Vector(1536), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_event_id"], ["site_events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_event_id"),
    )
    op.create_index(
        "ix_event_embeddings_embedding_hnsw",
        "event_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum("homeowner_to_contractor", "contractor_to_supplier", name="payment_direction"),
            nullable=False,
        ),
        sa.Column("counterparty_name", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(), server_default="INR", nullable=False),
        sa.Column("paid_on", sa.Date(), nullable=False),
        sa.Column("method", sa.Text(), nullable=True),
        sa.Column("reference_no", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("recorded", "confirmed", "disputed", name="payment_status"),
            server_default="recorded",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source_event_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_event_id"], ["site_events.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("language", sa.String(), server_default="en", nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "language")
    op.drop_table("payments")
    op.drop_index(
        "ix_event_embeddings_embedding_hnsw",
        table_name="event_embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("event_embeddings")
    op.drop_table("site_baselines")
    op.drop_table("permits")
    op.drop_table("decisions")
    # ### end Alembic commands ###
    # Inline sa.Enum auto-creates these types on upgrade but drop_table does not
    # remove them; drop explicitly so a re-upgrade doesn't hit "type exists".
    for enum_name in (
        "payment_status",
        "payment_direction",
        "permit_status",
        "decision_state",
        "decision_kind",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # vector extension left in place (shared, created by 0001).
