"""Owner Home dashboard endpoints (Phase B).

- ``GET /api/v1/dashboard/home?date=YYYY-MM-DD`` (any authed user): the Owner
  Brief home payload — headline counts, exceptions-first per-site cards with
  top risks + a 2x2 pulse grid, and a cold-start setup checklist. Read-only
  aggregation over B0 ``sites`` / ``site_events`` / ``site_baselines``; the
  brief itself is generated by :mod:`app.brief`.
- ``POST /api/v1/dashboard/decisions`` (owner/pm): create a
  :class:`app.models.Decision` from an inline Approve / Hold / Assign chip.

Visibility reuses :func:`app.auth.scoping.visible_site_ids` (owner/pm -> all
company sites; others -> none), so a supervisor hitting the owner home simply
sees an empty/cold-start state rather than another company's data.
"""
from __future__ import annotations

import datetime as dt
from collections import defaultdict
from uuid import UUID

from fastapi import APIRouter, Depends, Query
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.deps import get_current_user, require_role
from app.auth.scoping import visible_site_ids
from app.common.errors import AppError
from app.dashboard.aggregate import build_home
from app.dashboard.schemas import (
    DecisionCreateIn,
    DecisionOut,
    HomeOut,
)
from app.db import get_session
from app.models import (
    Decision,
    DecisionKind,
    Site,
    SiteBaseline,
    SiteEventModel,
    User,
    UserRole,
)

router = APIRouter(prefix="/api/v1/dashboard", tags=["dashboard"])

# Map an inline brief chip action onto the Decision state machine.
_ACTION_KIND = {
    "approve": DecisionKind.approval,
    "hold": DecisionKind.hold_payment,
    "assign": DecisionKind.generic,
}


@router.get("/home", response_model=HomeOut)
async def get_home(
    user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
    date: dt.date | None = Query(None),
) -> HomeOut:
    brief_date = date or (dt.datetime.now(dt.UTC).date() - dt.timedelta(days=1))
    prev_date = brief_date - dt.timedelta(days=1)

    visible = await visible_site_ids(session, user)
    if not visible:
        # No sites in scope -> cold start checklist (never a blank grid).
        payload = build_home([], {}, {})
        return HomeOut(brief_date=brief_date, **payload)

    sites = list(
        (await session.execute(select(Site).where(Site.id.in_(visible)))).scalars().all()
    )
    site_ids = [s.id for s in sites]

    events_by_site: dict[UUID, list[SiteEventModel]] = defaultdict(list)
    prev_events_by_site: dict[UUID, list[SiteEventModel]] = defaultdict(list)
    if site_ids:
        rows = (
            (
                await session.execute(
                    select(SiteEventModel).where(
                        SiteEventModel.site_id.in_(site_ids),
                        SiteEventModel.occurred_on.in_([brief_date, prev_date]),
                    )
                )
            )
            .scalars()
            .all()
        )
        for row in rows:
            if row.occurred_on == brief_date:
                events_by_site[row.site_id].append(row)
            else:
                prev_events_by_site[row.site_id].append(row)

    baselines_by_site: dict[UUID, SiteBaseline] = {}
    if site_ids:
        brows = (
            (
                await session.execute(
                    select(SiteBaseline).where(SiteBaseline.site_id.in_(site_ids))
                )
            )
            .scalars()
            .all()
        )
        baselines_by_site = {b.site_id: b for b in brows}

    payload = build_home(
        sites,
        events_by_site,
        baselines_by_site,
        prev_events_by_site=prev_events_by_site,
    )
    return HomeOut(brief_date=brief_date, **payload)


@router.post("/decisions", response_model=DecisionOut, status_code=201)
async def create_decision(
    body: DecisionCreateIn,
    user: User = Depends(require_role(UserRole.owner, UserRole.pm)),
    session: AsyncSession = Depends(get_session),
) -> DecisionOut:
    kind = _ACTION_KIND.get(body.action)
    if kind is None:
        raise AppError(
            422, "invalid_action", "action must be one of approve | hold | assign"
        )

    if body.site_id is not None:
        site = await session.get(Site, body.site_id)
        if site is None or site.company_id != user.company_id:
            raise AppError(404, "not_found", "Site not found")

    decision = Decision(
        company_id=user.company_id,
        site_id=body.site_id,
        kind=kind,
        title=body.title,
        detail=body.detail,
        raised_by=user.id,
        assigned_to=body.assigned_to,
        evidence_event_ids=body.evidence_event_ids,
    )
    session.add(decision)
    await session.commit()
    await session.refresh(decision)

    return DecisionOut(
        id=decision.id,
        company_id=decision.company_id,
        site_id=decision.site_id,
        kind=str(decision.kind),
        state=str(decision.state),
        title=decision.title,
        detail=decision.detail,
        assigned_to=decision.assigned_to,
        evidence_event_ids=list(decision.evidence_event_ids or []),
        created_at=decision.created_at,
    )
